### globals __dirname process ###

'use strict'
#had to added this after facing this error on vagrant Module build failed: ReferenceError: Promise is not defined
require 'coffee-script/register'
webpack = require 'webpack'
path = require('path')
HtmlWebpackPlugin = require('html-webpack-plugin')
conf = require 'rainier/conf'
{HTTP_PREFIX} = conf.get()

require('es6-promise').polyfill()
module.exports =
  devtool: 'source-map'
  entry: './src/app.jsx'
  output:
    path: path.join(__dirname, '/local/narrows-tracing/dist')
    publicPath: "#{HTTP_PREFIX}/dist/"
    filename: 'vizceral.[hash].bundle.js'
  resolve:
    extensions: [
      ''
      '.jsx'
      '.js'
    ]
    modulesDirectories: [ 'node_modules' ]
    fallback: path.join(__dirname, 'node_modules')
  resolveLoader: fallback: path.join(__dirname, 'node_modules')
  module: loaders: [
    {
      test: /\.jsx?$/
      exclude: /node_modules/
      loader: 'babel'
    }
    {
      test: /\.woff2?$/
      loader: 'url-loader?limit=10000&mimetype=application/font-woff'
    }
    {
      test: /\.otf$/
      loader: 'file-loader'
    }
    {
      test: /\.ttf$/
      loader: 'file-loader'
    }
    {
      test: /\.eot$/
      loader: 'file-loader'
    }
    {
      test: /\.svg$/
      loader: 'file-loader'
    }
    {
      test: /\.html$/
      loader: 'html'
    }
    {
      test: /\.css$/
      loader: 'style-loader!css-loader'
    }
  ]
  plugins: [
    new (webpack.ProvidePlugin)(
      jQuery: 'jquery'
      $: 'jquery')
    new webpack.DefinePlugin '__HIDE_DATA__': ! !process.env.HIDE_DATA
    new webpack.DefinePlugin 'HTTP_PREFIX': JSON.stringify HTTP_PREFIX
    new HtmlWebpackPlugin(
      title: 'Vizceral'
      template: './src/index.html'
      favicon: './src/favicon.ico'
      inject: true)
  ]

# ---
# generated by js2coffee 2.2.0
